"""add_combat_fields

Revision ID: 4cf0a3eb2283
Revises: 
Create Date: 2026-07-02 18:05:09.583068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf0a3eb2283'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('hp', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('max_hp', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('characters', sa.Column('xp', sa.Integer(), nullable=False))
    op.alter_column('characters', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('characters', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('characters', 'char_class',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('characters', 'char_class',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('characters', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('characters', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('characters', 'xp')
    op.drop_column('characters', 'level')
    op.drop_column('characters', 'max_hp')
    op.drop_column('characters', 'hp')
    # ### end Alembic commands ###
